# Generated by Django 3.2.2 on 2021-07-05 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20210702_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='api.project'),
        ),
        migrations.AlterField(
            model_name='constants',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constants', to=settings.AUTH_USER_MODEL),
        ),
    ]
