# Generated by Django 3.2.2 on 2021-07-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_case_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='params',
            new_name='common_params',
        ),
        migrations.AddField(
            model_name='case',
            name='current_params',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='planned_params',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
