# Generated by Django 3.2.2 on 2021-07-11 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_remove_case_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constants',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='constants', to=settings.AUTH_USER_MODEL),
        ),
    ]
