# Generated by Django 3.2.2 on 2021-07-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210712_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='constants',
            name='city_climate',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
