# Generated by Django 3.2.2 on 2021-07-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_constants_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='constants',
            name='file',
            field=models.FileField(default=None, max_length=50, upload_to=''),
            preserve_default=False,
        ),
    ]
