# Generated by Django 3.2.2 on 2021-07-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_constants_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constants',
            name='file',
            field=models.FileField(upload_to='constants/'),
        ),
    ]
