# Generated by Django 3.2.2 on 2021-07-11 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_constants_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constants',
            name='file',
        ),
    ]
