# Generated by Django 3.2.2 on 2021-07-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_constants_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='constants',
            name='file',
            field=models.FileField(default=None, upload_to='constants/'),
            preserve_default=False,
        ),
    ]
