# Generated by Django 3.2.2 on 2021-07-15 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_constants_city_climate'),
        ('api', '0010_constants_file'),
    ]

    operations = [
    ]
