# Generated by Django 3.2.2 on 2021-07-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210729_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constants',
            name='city_climate',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='constants',
            name='default_uncertainty',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='constants',
            name='envelope_windows',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='constants',
            name='heating_dhw',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='constants',
            name='other_thermal_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='constants',
            name='thermal_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='constants',
            name='uncertain_variables',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='constants',
            name='variable_costs',
            field=models.JSONField(default=dict),
        ),
    ]
