# Generated by Django 3.2.2 on 2021-08-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210729_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='constants',
            name='file_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
