# Generated by Django 3.2.2 on 2021-10-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_constants_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rating_data',
            field=models.JSONField(default=dict),
        ),
    ]
