# Generated by Django 3.2.2 on 2021-10-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_project_rating_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='report_data',
            field=models.JSONField(default=dict),
        ),
    ]
