# Generated by Django 3.2.2 on 2021-11-09 12:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_project_report_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rating_data',
            field=models.JSONField(default=api.models.get_default_rating_data),
        ),
    ]
