# Generated by Django 3.2.2 on 2021-11-12 20:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_project_rating_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='report_data',
            field=models.JSONField(default=api.models.get_default_report_data),
        ),
    ]
