# Generated by Django 3.2.2 on 2022-02-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_bpcase_bpinvestment_bpproject_ocproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpinvestment',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
